version: '3.9'

services:
  spring:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: curso_spring
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
